sonar.projectKey=sonarqube-app
sonar.projectName=SonarQube Demo App
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/migrations/**
sonar.qualitygate.wait=true
